"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import { LogOut, Clock } from "lucide-react";
import { useIdleTimeout } from "@/hooks/useIdleTimeout";

const IDLE_TIMEOUT_MS  = 60 * 60 * 1000; // 1 hour
const WARN_BEFORE_MS   =  5 * 60 * 1000; // warn 5 min before

async function serverLogout() {
  try {
    await fetch("/api/auth/logout", { method: "POST" });
  } catch {
    // best-effort
  }
}

export default function IdleGuard() {
  const router = useRouter();
  const [showWarning, setShowWarning]   = useState(false);
  const [secondsLeft, setSecondsLeft]   = useState(WARN_BEFORE_MS / 1000);
  const countdownRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const logout = useCallback(async () => {
    setShowWarning(false);
    if (countdownRef.current) clearInterval(countdownRef.current);
    await serverLogout();
    router.replace("/login");
  }, [router]);

  const handleWarning = useCallback(() => {
    setSecondsLeft(WARN_BEFORE_MS / 1000);
    setShowWarning(true);
  }, []);

  const handleStayLoggedIn = useCallback(() => {
    setShowWarning(false);
    if (countdownRef.current) clearInterval(countdownRef.current);
    // Activity was generated by clicking the button, so the idle timer resets automatically
  }, []);

  // Countdown ticker when the warning modal is visible
  useEffect(() => {
    if (!showWarning) return;

    countdownRef.current = setInterval(() => {
      setSecondsLeft((s) => {
        if (s <= 1) {
          clearInterval(countdownRef.current!);
          return 0;
        }
        return s - 1;
      });
    }, 1000);

    return () => {
      if (countdownRef.current) clearInterval(countdownRef.current);
    };
  }, [showWarning]);

  useIdleTimeout({
    timeout:       IDLE_TIMEOUT_MS,
    warningBefore: WARN_BEFORE_MS,
    onWarning:     handleWarning,
    onIdle:        logout,
  });

  if (!showWarning) return null;

  const minutes = Math.floor(secondsLeft / 60);
  const secs    = String(secondsLeft % 60).padStart(2, "0");
  const display = minutes > 0 ? `${minutes}:${secs}` : `${secondsLeft}s`;

  return (
    <div
      className="fixed inset-0 z-50 flex items-end justify-center"
      style={{ background: "rgba(18,42,26,0.5)" }}
      aria-modal="true"
      role="alertdialog"
      aria-labelledby="idle-title"
      aria-describedby="idle-desc"
    >
      <div
        className="w-full max-w-[430px] rounded-t-3xl p-6 pb-10 animate-fade-slide-up"
        style={{ background: "#ffffff" }}
      >
        {/* Handle */}
        <div className="w-10 h-1 rounded-full mx-auto mb-6" style={{ background: "#e4e4e4" }} />

        {/* Icon + countdown ring */}
        <div className="flex justify-center mb-5">
          <div
            className="w-16 h-16 rounded-2xl flex items-center justify-center"
            style={{ background: "#FEF9C3" }}
          >
            <Clock size={30} color="#CA8A04" strokeWidth={1.5} />
          </div>
        </div>

        <h2
          id="idle-title"
          className="font-display text-xl font-semibold text-center mb-2"
          style={{ color: "#122A1A" }}
        >
          Nog steeds aanwezig?
        </h2>

        <p
          id="idle-desc"
          className="text-sm text-center mb-1"
          style={{ color: "#7a8f82" }}
        >
          Je wordt automatisch uitgelogd over
        </p>

        {/* Countdown */}
        <p
          className="font-display text-3xl font-semibold text-center mb-6"
          style={{ color: secondsLeft <= 30 ? "#DC2626" : "#304C3A" }}
        >
          {display}
        </p>

        <button
          onClick={handleStayLoggedIn}
          className="btn-primary mb-3"
        >
          Ingelogd blijven
        </button>

        <button
          onClick={logout}
          className="btn-secondary flex items-center justify-center gap-2"
        >
          <LogOut size={16} />
          Nu uitloggen
        </button>
      </div>
    </div>
  );
}